title: Chords - App de cifras
email: gustavomarques.gml@gmail.com
description: 
  Documentação do aplicativo Chords - App de cifras
  Um aplicativo para músicos que desejam aprender a tocar suas músicas favoritas.
twitter_username: gustavo_m_gm
github_username:  gustavolima00

url: https://chords-org.github.io/docs/

theme: just-the-docs
plugins:
  - jekyll-default-layout
sass:
  quiet_deps: true